USE RAPortal;
DROP TABLE EVALUATION;
CREATE TABLE IF not exists EVALUATION(
PARTICIPANTID VARCHAR(10) NOT null,
PROGRAMMINGLANGUAGE VARCHAR(15) NOT NULL,
LANGUAGELEVEL VARCHAR(15) NOT NULL,
CODENUMBER INT(1) NOT NULL,
QUESTION_NUMBER INT(1) NOT NULL,
RECORDED_ANSWER VARCHAR(15) NOT NULL,
CORRECT_ANSWER VARCHAR(15) NOT NULL,
DECISION VARCHAR(10) NOT NULL,
SCORE INT(1) NOT NULL
);

SELECT *
FROM INFORMATION_SCHEMA.COLUMNS
WHERE table_name = 'AdminDATA';

Describe EVALUATION;